Models/Pecas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace lojaDePecasDeCarro.Models
{
    public class Pecas
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Decimal Price { get; set; }
        public bool InStock { get; set; }

    }
}

Controllers/PecasController.cs
using lojaDePecasDeCarro.Data;
using lojaDePecasDeCarro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lojaDePecasDeCarro.Controllers
{
    public class PecasController : Controller
    {
        private PecasBO pbo = new PecasBO();
        public PecasController()
        {
            
        }

        // GET: Pecas
        public ActionResult Index(PecasBO model)
        {

            var ListItem = pbo.GetPecas().ToList();
            
            return View(ListItem);
        }

        // GET: Pecas/Details/5
        
        [HttpGet]
        public ActionResult FindById()
        {
           return View();
        }

        [HttpPost]
        public ActionResult FindById(int? id)
        {
            var ListById = pbo.GetById(id);

            if(ListById != null)
            {
                return View(ListById);
            }
            return View();

        }
                              
        [HttpPost]
        public ActionResult Create(Pecas pecas)
        {
            try
            {
                pbo.Create(pecas);
                return RedirectToAction("Index");
            }
            catch (Exception err)
            {
                throw err;
            }

           
        }


        [HttpGet]// GET: Pecas/Create
        public ActionResult Create()
        {

            return View();
        }

      
        // GET: Pecas/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var ListById = pbo.GetById(id);

            if (ListById != null)
            {
                return View(ListById);
            }
            return View();
        }

        // POST: Pecas/Edit/5
        [HttpPost]
        public ActionResult Edit(Pecas pecas)
        {
            try
            {
                pbo.Edit(pecas);
                return RedirectToAction("Index");
            }
            catch (Exception err)
            {
                throw err;
            }
            
        }

        // GET: Pecas/Delete/5
        public ActionResult Delete(int? id)
        {
            var ListById = pbo.GetById(id);

            if (ListById != null)
            {
                return View(ListById);
            }
            return View();
        }

        // POST: Pecas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                pbo.Delete(id);

               return RedirectToAction("Index");
           }
            catch
            {
                return View();
            }
        }
    }
}

Views/Pecas/Create.cshtml
@model lojaDePecasDeCarro.Models.Pecas

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pecas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.InStock)
                    @Html.ValidationMessageFor(model => model.InStock, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, htmlAttributes: new { @class = "btn btn-default" })
</div>

Views/Pecas/Delete.cshtml
@model lojaDePecasDeCarro.Models.Pecas

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pecas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InStock)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Pecas/Edit.cshtml
@model lojaDePecasDeCarro.Models.Pecas

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<div class="row">
    <div class="col">
        @using (Html.BeginForm())
        {
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Has Stock</th>
                </tr>

                <tr>
                    <td>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                    </td>
                    <td>
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.InStock, new { htmlAttributes = new { @class = "" } })
                    </td>
                </tr>

            </table>
            <input type="submit" value="Update" class="btn btn-primary" />
        }



    </div>
</div>

Views/Pecas/findById.cshtml
@model lojaDePecasDeCarro.Models.Pecas

<h1>Hello World</h1>

<div class="row">
    <div class="col">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(m => Model.Id)
                @Html.TextBoxFor(m => Model.Id, new { @class = "form-control" })
            </div>
            <input type="submit" name="Buscar" class="btn btn-primary" />


        }


        @using (Html.BeginForm())
        {
            <table class="table">
                                       
                    <tr>
                        <td>
                            @Html.DisplayFor(Model => Model.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(Model => Model.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(Model => Model.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(Model => Model.InStock)
                        </td>
                    </tr>
                    
                </table>
               
            }



        </div>
</div>

Views/Pecas/index.cshtml
@model  List<lojaDePecasDeCarro.Models.Pecas>

<h1>Auto items list</h1>

@Html.ActionLink("Create", "Create", new { }, htmlAttributes: new { @class = "btn btn-primary" })



<table class="table">
    <thead>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">Stock</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>@item.Price</td>
                        @if (@item.InStock == true)
                        {
                            <td>In Stock</td>
                        }
                        else
                        {
                            <td>Out of Stock</td>
                        }
                        <td>

                            @Html.ActionLink("Delete", "Delete", new { item.Id }, htmlAttributes: new { @class = "btn btn-danger" })
                            @Html.ActionLink("Edit", "Edit", new { item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                        </td>
                    </tr>


                }

            </tbody>

        </table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Itens List", "Index", "Pecas", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Create", "Create", "Pecas", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("FindById", "FindById", "Pecas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>